.PHONY: clean All

All:
	@echo "----------Building project:[ Ejemplo6-sesion2 - Debug ]----------"
	@cd "Ejemplo6-sesion2" && "$(MAKE)" -f  "Ejemplo6-sesion2.mk"
clean:
	@echo "----------Cleaning project:[ Ejemplo6-sesion2 - Debug ]----------"
	@cd "Ejemplo6-sesion2" && "$(MAKE)" -f  "Ejemplo6-sesion2.mk" clean
