.PHONY: clean All

All:
	@echo "----------Building project:[ Ejemplo_8 - Debug ]----------"
	@cd "Ejemplo_8" && "$(MAKE)" -f  "Ejemplo_8.mk"
clean:
	@echo "----------Cleaning project:[ Ejemplo_8 - Debug ]----------"
	@cd "Ejemplo_8" && "$(MAKE)" -f  "Ejemplo_8.mk" clean
