.PHONY: clean All

All:
	@echo "----------Building project:[ NodoPila - Debug ]----------"
	@cd "NodoPila" && "$(MAKE)" -f  "NodoPila.mk"
clean:
	@echo "----------Cleaning project:[ NodoPila - Debug ]----------"
	@cd "NodoPila" && "$(MAKE)" -f  "NodoPila.mk" clean
